# Generated by Django 3.2.5 on 2021-07-18 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, null=True, unique=True, verbose_name='UserName')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('last_name', models.CharField(max_length=255, null=True, verbose_name='Last Name')),
                ('image', models.ImageField(null=True, upload_to='perfil/', verbose_name='Image')),
                ('email', models.EmailField(max_length=255, null=True, unique=True, verbose_name='Email')),
                ('cellPhone', models.CharField(max_length=30, verbose_name='Cellphone')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
    ]
